original/trytry/trytry/Models/wedding.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    public partial class wedding
    {
        public int HallId { get; set; }

        [DisplayName("CityName")]
        [Required(ErrorMessage = "CityName is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]


        public string CityName { get; set; }


        [DisplayName("HallName")]
        [Required(ErrorMessage = "HallName is required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]


        public string HallName { get; set; }



        [DisplayName("facilities")]
        [Required(ErrorMessage = "facilities are required.")]
        [StringLength(150)]
        [DataType(DataType.Text)]
        public string facilities { get; set; }



        [Required]
        public byte[] image { get; set; }



        [DisplayName("FoodItems")]
        [Required(ErrorMessage = "FoodItems are required.")]
        [StringLength(50)]
        [DataType(DataType.Text)]

        public string fooditems { get; set; }




        [Required(ErrorMessage = "capacity is required.")]
        [StringLength(50)]
        public Nullable<int> capacity { get; set; }

        [DisplayName("Date")]
        [Required(ErrorMessage = "Date is required.")]
        [StringLength(50)]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> date { get; set; }

        [DisplayName("Time")]
        [Required(ErrorMessage = "time is required.")]
        [StringLength(50)]
        [DataType(DataType.DateTime)]
        public Nullable<System.TimeSpan> time { get; set; }


        [DisplayName("budget")]
        [Required(ErrorMessage = "budget is required.")]
        [StringLength(50)]
        [DataType(DataType.Currency)]
        public Nullable<int> budget { get; set; }


        [DisplayName("address")]
        [Required(ErrorMessage = "address is required.")]
        [StringLength(150)]
        [DataType(DataType.PostalCode)]
        public string address { get; set; }
    }
}

original/trytry/trytry/Controllers/WeddingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using trytry.Models;
using System.IO;
using System.Data.Entity.Infrastructure;

namespace trytry.Controllers
{
    public class WeddingController : Controller
    {
        hotelEntities8 dc = new hotelEntities8();
        string connectionstring = @"Data Source=DESKTOP-1M6H1PO\ANUMSQL;Initial Catalog=hotel;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework";
        [HttpGet]
        public ActionResult Index()
        {
            List<wedding1> lists = new List<wedding1>();
            lists = dc.wedding1.ToList();
            return View(lists);
        }



        // GET: Wedding/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Wedding/Create
        [HttpPost]
        public ActionResult Create(wedding1 weddingmodel)
        {
            try
            {
                string filename = Path.GetFileNameWithoutExtension(weddingmodel.ImageFile.FileName);
                string extension = Path.GetExtension(weddingmodel.ImageFile.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                weddingmodel.image = "~/Image/" + filename;
                filename = Path.Combine(Server.MapPath("~/Image/"), filename);
                weddingmodel.ImageFile.SaveAs(filename);
                using (hotelEntities8 dc = new hotelEntities8())
                {

                    dc.wedding1.Add(weddingmodel);
                    dc.SaveChanges();
                }

            }
            catch (Exception ex)
            {
                return View(ex);

            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Successful";
            return RedirectToAction("Index");

        }

       
        // GET: Wedding/Edit/5
        public ActionResult Edit(int id)
        {
            wedding1 weddingmodel = new wedding1();
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Select * from wedding1 where HallId = @HallId";
                SqlDataAdapter ada = new SqlDataAdapter(query, con);
                ada.SelectCommand.Parameters.AddWithValue("@HallId", id);
                ada.Fill(dt);
                con.Close();
            }
            if (dt.Rows.Count == 1)
            {
                weddingmodel.HallId = Convert.ToInt32(dt.Rows[0][0].ToString());
                weddingmodel.CityName = dt.Rows[0][1].ToString();
                weddingmodel.HallName = dt.Rows[0][2].ToString();
                weddingmodel.facilities = dt.Rows[0][3].ToString();
                weddingmodel.capacity = Convert.ToInt32(dt.Rows[0][6].ToString());
                weddingmodel.budget = Convert.ToInt32(dt.Rows[0][9].ToString());
                weddingmodel.address = dt.Rows[0][10].ToString();

                return View(weddingmodel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Wedding/Edit/5
        [HttpPost]
        public ActionResult Edit(wedding1 weddingmodel)
        {
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Update wedding1 set CityName = @CityName, HallName = @HallName, facilities = @facilities, capacity = @capacity, budget = @budget, address = @address where HallId = @HallId";
                SqlCommand cmd = new SqlCommand(query, con);
                cmd.Parameters.AddWithValue("@HallId", weddingmodel.HallId);
                cmd.Parameters.AddWithValue("@CityName", weddingmodel.CityName);
                cmd.Parameters.AddWithValue("@HallName", weddingmodel.HallName);
                cmd.Parameters.AddWithValue("@facilities", weddingmodel.facilities);
                cmd.Parameters.AddWithValue("@capacity", weddingmodel.capacity);
                cmd.Parameters.AddWithValue("@budget", weddingmodel.budget);
                cmd.Parameters.AddWithValue("@address", weddingmodel.address);

                cmd.ExecuteNonQuery();

            }
            return RedirectToAction("Index");
        }

        // GET: Wedding/Delete/5
        public ActionResult Delete(int id)
        {
            wedding1 weddingmodel = new wedding1();
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Select * from wedding1 where HallId = @HallId";
                SqlDataAdapter ada = new SqlDataAdapter(query, con);
                ada.SelectCommand.Parameters.AddWithValue("@HallId", id);
                ada.Fill(dt);
                con.Close();
            }
            if (dt.Rows.Count == 1)
            {
                weddingmodel.HallId = Convert.ToInt32(dt.Rows[0][0].ToString());
                weddingmodel.CityName = dt.Rows[0][1].ToString();
                weddingmodel.HallName = dt.Rows[0][2].ToString();
                weddingmodel.facilities = dt.Rows[0][3].ToString();
                weddingmodel.capacity = Convert.ToInt32(dt.Rows[0][6].ToString());

                weddingmodel.budget = Convert.ToInt32(dt.Rows[0][9].ToString());
                weddingmodel.address = dt.Rows[0][10].ToString();
                return View(weddingmodel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Wedding/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Delete From wedding1 where HallId = @HallId";
                SqlCommand cmd = new SqlCommand(query, con);
                cmd.Parameters.AddWithValue("@HallId", id);


                cmd.ExecuteNonQuery();

            }
            return RedirectToAction("Index");
        }
    }
}

original/trytry/trytry/Views/Wedding/Create.cshtml
@model trytry.Models.wedding1

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Wedding", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>wedding1</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
       
        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HallName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HallName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HallName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.facilities, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.facilities, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.facilities, "", new { @class = "text-danger" })
            </div>
        </div>

      
        <div class="form-group">
            @Html.LabelFor(model => model.fooditems, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fooditems, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fooditems, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.capacity, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.budget, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.budget, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.budget, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

original/trytry/trytry/Views/Wedding/Delete.cshtml
@model trytry.Models.wedding1

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WeddingHallModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.HallId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HallId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HallName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HallName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.facilities)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.facilities)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fooditems)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fooditems)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.capacity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.capacity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.time)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.time)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.budget)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.budget)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

original/trytry/trytry/Views/Wedding/Edit.cshtml
@model trytry.Models.wedding1

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>WeddingHallModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HallId)


        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HallName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HallName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HallName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.facilities, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.facilities, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.facilities, "", new { @class = "text-danger" })
            </div>
        </div>

       
        <div class="form-group">
            @Html.LabelFor(model => model.capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.capacity, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.budget, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.budget, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.budget, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

original/trytry/trytry/Views/Wedding/Index.cshtml
@model IEnumerable<trytry.Models.wedding1>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}
<div class="container">
    <h2 class="text-center">Wedding Hall</h2>
    @foreach (var item in Model)
    {
        <div class="col-md-3" style="margin-bottom:25px">
            <div class="thumbnail">
                <h2 class="text-center">@item.CityName</h2>
                <div class="image" style="margin-bottom:20px">
                    <img class="img-responsive" src="@Url.Content(item.image)" height="350" width="240" />
                </div>
                <div class="caption" style="border-top:3px solid #808080">
                    <h2>@item.HallName</h2>
                    
                    <h4>Address:@item.address</h4>
                    <h5>Price per person:@item.budget $</h5>
                    <h6>Capacity:@item.capacity</h6>
                    <h7>Food:@item.fooditems</h7>
                    <h8>Facilities:@item.facilities</h8>
                    <p>
                        @Html.ActionLink("Edit", "Edit", new { id = item.HallId })`
                        @Html.ActionLink("Delete", "Delete", new { id = item.HallId })
                    </p>
                </div>

            </div>
        </div>
    }
</div>

    
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.CityId })*@
    @Html.ActionLink("Add Wedding Hall", "Create")
</p>


<p>@Html.ActionLink("Back To List", "Index", "Admin")</p>