original/trytry/trytry/Models/bookingtable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class bookingtable
    {
        public int BookingId { get; set; }
        public Nullable<int> TableId { get; set; }
        public string HallName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "User Name")]
        [RegularExpression("[A-Za-z]*", ErrorMessage = "Invalid Name ")]
        public string Name { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Cell #")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Entered phone format is not valid.(3*********")]
        public Nullable<int> Phone_No { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [RegularExpression("([a-zA-Z0-9_ .&'-]+)", ErrorMessage = "Invalid.")]
        public string Address { get; set; }


        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "Check in Date")]
        [DataType(DataType.Date)]
        public string checkindate { get; set; }


        public Nullable<System.TimeSpan> Time { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "No of Persons")]
        [MinLength(1)]
        [RegularExpression("[^0-9]", ErrorMessage = "Input must be numeric")]
        public Nullable<int> personno { get; set; }
    
        public virtual tableadmin1 tableadmin1 { get; set; }
        public virtual tablebooking tablebooking { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}

original/trytry/trytry/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using trytry.Models;

namespace trytry.Controllers
{
    public class BookingController : Controller
    {
        string connectionstring = @"Data Source=DESKTOP-1M6H1PO\ANUMSQL;Initial Catalog=hotel;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework";
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult WeddingBooking()
        {
            return View();
        }

        public ActionResult TableBooking()
        {
            return View();
        }

        public ActionResult ConferenceBooking()
        {
            return View();
        }

        public ActionResult RoomBooking()
        {
            return View();
        }

        public ActionResult CreateAccount()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        // GET: Booking/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Booking/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Booking/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Booking/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Booking/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

original/trytry/trytry/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using trytry.Models;

namespace trytry.Controllers
{
    public class BookingsController : Controller
    {
        string connectionstring = @"Data Source=DESKTOP-1M6H1PO\ANUMSQL;Initial Catalog=hotel;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework";
        // GET: Bookings
        public ActionResult Index()
        {
            return View();
        }

        // GET: Bookings/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Bookings/Create
        public ActionResult Room_Booking()
        {
            return View(new hotel());
        }

        // POST: Bookings/Create
        [HttpPost]
        public ActionResult Room_Booking(hotel hotel)
        {
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                //string filepath = Path.GetFileName(image1.FileName);
                //string savedfilename = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, Path.GetFileName(image1.FileName));
                //image1.SaveAs(Server.MapPath("~/Desktop/Images/" + filepath));
                string query = "insert into hotel(avaliablerooms,checkindate,checkoutdate) values (@avaliablerooms,@checkindate,@checkoutdate)";
                SqlCommand cmd = new SqlCommand(query, con);
                cmd.Parameters.AddWithValue("@avaliablerooms", hotel.avaliablerooms);
                cmd.Parameters.AddWithValue("@checkindate", hotel.checkindate);
                cmd.Parameters.AddWithValue("@checkoutdate", hotel.checkoutdate);
                //


                //string fileName = Path.GetFileNameWithoutExtension(citymodel.ImageFile.FileName);
                //string extension = Path.GetExtension(citymodel.ImageFile.FileName);
                //fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                //citymodel.image = "~/Image/" + fileName;
                //fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                //citymodel.ImageFile.SaveAs(fileName);
                //using (hotelEntities2 db = new hotelEntities2())
                //{
                //    db.Cities.Add(citymodel);
                //    db.SaveChanges();
                //}



                cmd.ExecuteNonQuery();
                con.Close();


            }
            return RedirectToAction("Index");
        }

        // GET: Bookings/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Bookings/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Bookings/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Bookings/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }





        //[HttpPost]
        //public ActionResult Conference_Booking(int id)
        //{
        //    //hotel conferencemodel = new hotel();
        //DataTable dt = new DataTable();
        //using (SqlConnection con = new SqlConnection(connectionstring))
        //{
        //    con.Open();
        //    string query = "Select * from hotel where CityId = @CityId";
        //    SqlDataAdapter ada = new SqlDataAdapter(query, con);
        //    ada.SelectCommand.Parameters.AddWithValue("@CityId", id);
        //    ada.Fill(dt);
        //    con.Close();
        //}
        //if (dt.Rows.Count == 1)
        //{
        //    conferencemodel.CityId = Convert.ToInt32(dt.Rows[0][0].ToString());
        //    //conferencemodel.CityName = dt.Rows[0][1].ToString();
        //    //conferencemodel.HallName = dt.Rows[0][2].ToString();
        //    //conferencemodel.facilities = dt.Rows[0][3].ToString();
        //    //conferencemodel.capacity = Convert.ToInt32(dt.Rows[0][6].ToString());
        //    //conferencemodel.budget = Convert.ToInt32(dt.Rows[0][9].ToString());
        //    //conferencemodel.address = dt.Rows[0][10].ToString();




        //    return View(conferencemodel);
        //}
        //else
        //{
        //    return View();
        //}









        // GET: Bookings/Create
        public ActionResult Conference_Booking()
        {
            return View(new hotel());
        }

        // POST: Bookings/Create
        [HttpPost]
        public ActionResult Conference_Booking(hotel hotel)
        {
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                //string filepath = Path.GetFileName(image1.FileName);
                //string savedfilename = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, Path.GetFileName(image1.FileName));
                //image1.SaveAs(Server.MapPath("~/Desktop/Images/" + filepath));
                string query = "insert into hotel(avaliableconferencerooms,checkindate,checkoutdate) values (@avaliableconferencerooms,@checkindate,@checkoutdate)";
                SqlCommand cmd = new SqlCommand(query, con);
                cmd.Parameters.AddWithValue("@avaliableconferencerooms", hotel.avaliablerooms);
                cmd.Parameters.AddWithValue("@checkindate", hotel.checkindate);
                cmd.Parameters.AddWithValue("@checkoutdate", hotel.checkoutdate);
                //


                //string fileName = Path.GetFileNameWithoutExtension(citymodel.ImageFile.FileName);
                //string extension = Path.GetExtension(citymodel.ImageFile.FileName);
                //fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                //citymodel.image = "~/Image/" + fileName;
                //fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                //citymodel.ImageFile.SaveAs(fileName);
                //using (hotelEntities2 db = new hotelEntities2())
                //{
                //    db.Cities.Add(citymodel);
                //    db.SaveChanges();
                //}



                cmd.ExecuteNonQuery();
                con.Close();


            }
            return RedirectToAction("Index");
        }




    }
}
    

original/trytry/trytry/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace trytry.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Gallery()
        {
            return View();
        }

        public ActionResult Services()
        {
            return View();
        }

        public ActionResult Cities()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        // GET: User/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: User/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: User/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: User/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

original/trytry/trytry/Views/Shared/_Booking.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Luscious a Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

    <script type="application/x-javascript">
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <link href="@Url.Content("~/Content/mytemplate/")css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="@Url.Content("~/Content/mytemplate/")css/wickedpicker.css" rel="stylesheet" type='text/css' media="all" />
    <link href="@Url.Content("~/Content/mytemplate/")css/easy-responsive-tabs.css" rel='stylesheet' type='text/css' />
    <link href="@Url.Content("~/Content/mytemplate/")css/style.css" rel='stylesheet' type='text/css' />
    <link href="@Url.Content("~/Content/mytemplate/")css/font-awesome.css" rel="stylesheet">
    <link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic'
          rel='stylesheet' type='text/css'>
</head>
<body>

    <div class="header" id="home">
        <!--/top-bar-->
        <div class="top-bar">
            <div class="header-top_w3layouts">
                <div class="forms">
                    <p><span class="fa fa-map-marker" aria-hidden="true"></span>Parma Via Modena,BO, Italy</p>
                    <p><span class="fa fa-envelope-o" aria-hidden="true"></span> <a href="mailto:info@example.com">info@example.com</a></p>
                </div>
                <ul class="top-right-info">
                    <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                    <li><a href="#"><i class="fa fa-pinterest-p" aria-hidden="true"></i></a></li>

                </ul>
                <div class="search">
                    <div class="cd-main-header">
                        <ul class="cd-header-buttons">
                            <li><a class="cd-search-trigger" href="#cd-search"> <span></span></a></li>
                        </ul>
                        <!-- cd-header-buttons -->
                    </div>
                    <div id="cd-search" class="cd-search">
                        <form action="#" method="post">
                            <input name="Search" type="search" placeholder="Click enter after typing...">
                        </form>
                    </div>
                </div>
                <div class="clearfix"></div>

            </div>
            <div class="header-nav">
                <nav class="navbar navbar-default">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <h1><a class="navbar-brand" href="index.html">R<span>eservation</span></a></h1>
                    </div>
                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse nav-wil" id="bs-example-navbar-collapse-1">
                        <nav>
                            <ul class="top_nav">
                                
                                <li>@Html.ActionLink("Wedding Hall Booking", "WeddingBooking", "Booking")</li>
                                <li>@Html.ActionLink("Conference Hall Booking", "ConferenceBooking", "Booking")</li>
                                <li>@Html.ActionLink("Room Booking", "RoomBooking", "Booking")</li>
                                <li>@Html.ActionLink("Table Booking", "Table Booking", "User")</li>
                                <li>@Html.ActionLink("Login", "Login", "Booking")</li>
                                <li><a class="scroll" href="#mail">Login</a></li>
                            </ul>
                        </nav>
                    </div>
                </nav>

            </div>
        </div>
        <!--//top-bar-->
        <!-- banner-text -->
        <div class="slider">
            <div class="callbacks_container">
                <ul class="rslides callbacks callbacks1" id="slider4">
                    <li id="callbacks1_s0" class="" style="display: block; float: none; position: absolute; opacity: 0; z-index: 1; transition: opacity 1000ms ease-in-out 0s;">
                        <div class="banner-top">
                            <div class="banner-info_agile_w3ls">
                                <h3>HOTEL <span>MANAGEMENT</span> SYSTEM</h3>
                                <p>Small change,Big differences.</p>
                                <a href="#about" class="scroll">Read More <i class="fa fa-caret-right" aria-hidden="true"></i></a>
                                <a href="#mail" class="scroll">Contact Us <i class="fa fa-caret-right" aria-hidden="true"></i></a>
                            </div>

                        </div>
                    </li>
                    <li id="callbacks1_s1" class="callbacks1_on" style="display: block; float: left; position: relative; opacity: 1; z-index: 2; transition: opacity 1000ms ease-in-out 0s;">
                        <div class="banner-top1">
                            <div class="banner-info_agile_w3ls">
                                <h3>HOTEL <span> MANAGEMENT</span> SYSTEM</h3>
                                <p>Small change,Big differences.</p>
                                <a href="#about" class="scroll">Read More <i class="fa fa-caret-right" aria-hidden="true"></i></a>
                                <a href="#mail" class="scroll">Contact Us <i class="fa fa-caret-right" aria-hidden="true"></i></a>
                            </div>

                        </div>
                    </li>
                    <li id="callbacks1_s2" class="" style="display: block; float: none; position: absolute; opacity: 0; z-index: 1; transition: opacity 1000ms ease-in-out 0s;">
                        <div class="banner-top2">
                            <div class="banner-info_agile_w3ls">
                                <h3>HOTEL <span>MANAGEMENT</span> SYSTEM</h3>
                                <p>Small change,Big differences.</p>
                                <a href="#about" class="scroll">Read More <i class="fa fa-caret-right" aria-hidden="true"></i></a>
                                <a href="#mail" class="scroll">Contact Us <i class="fa fa-caret-right" aria-hidden="true"></i></a>
                            </div>

                        </div>
                    </li>
                    <li id="callbacks1_s3" class="" style="display: block; float: none; position: absolute; opacity: 0; z-index: 1; transition: opacity 1000ms ease-in-out 0s;">
                        <div class="banner-top3">
                            <div class="banner-info_agile_w3ls">
                                <h3>HOTEL <span> MANAGEMENT</span> SYSTEM</h3>
                                <p>Small change,Big differences.</p>
                                <a href="#about" class="scroll">Read More <i class="fa fa-caret-right" aria-hidden="true"></i></a>
                                <a href="#mail" class="scroll">Contact Us <i class="fa fa-caret-right" aria-hidden="true"></i></a>
                            </div>

                        </div>
                    </li>
                </ul><a href="#" class="callbacks_nav callbacks1_nav prev">Previous</a><a href="#" class="callbacks_nav callbacks1_nav next">Next</a><ul class="callbacks_tabs callbacks1_tabs"><li class="callbacks1_s1"><a href="#" class="callbacks1_s1">1</a></li><li class="callbacks1_s2 callbacks_here"><a href="#" class="callbacks1_s2">2</a></li><li class="callbacks1_s3"><a href="#" class="callbacks1_s3">3</a></li><li class="callbacks1_s4"><a href="#" class="callbacks1_s4">4</a></li></ul>
            </div>
            <div class="clearfix"> </div>

            <!--banner Slider starts Here-->
        </div>
        <!-- //Modal1 -->
        <!--//Slider-->
    </div>

    </div>
    <div>@RenderBody()</div>
</body>
</html>

original/trytry/trytry/Views/Shared/_Mytemplate1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Hotel Management System", "", "", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("RoomBooking", "Cities", "Home")</li>
                        <li>@Html.ActionLink("Wedding Hall Booking", "Cities_wedding", "Home")</li>
                        <li>@Html.ActionLink("Coference Hall Booking", "Cities_conference", "Home")</li>
                    <li>@Html.ActionLink("Table Booking", "Cities_table", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)






</body>
</html>

original/trytry/trytry/Views/Shared/_admin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotel Management System", "", "", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)




</body>
</html>

original/trytry/trytry/Views/Shared/_mytemplate.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hotel Management System", "", "", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)



    
</body>
</html>