original/trytry/trytry/Models/City.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace trytry.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    using System.ComponentModel.DataAnnotations;
    
    public partial class City
    {
        public int CityId { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string CityName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string image { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}

original/trytry/trytry/Controllers/CityController.cs
using trytry.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;

using System.Data.SqlClient;

using System.IO;
using System.Data.Entity.Infrastructure;

namespace trytry.Controllers
{
    public class CityController : Controller
    {
        hotelEntities8 dc = new hotelEntities8();
        string connectionstring = @"Data Source=DESKTOP-1M6H1PO\ANUMSQL;Initial Catalog=hotel;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework";
        private object db;

        [HttpGet]
        public ActionResult Index()
        {
            List<City> lists = new List<City>();
            lists = dc.Cities.ToList();
            return View(lists);
        }

      
        [HttpGet]
        // GET: City/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: City/Create
        [HttpPost]
        public ActionResult Create(City city)
        {

            try
            {
                string filename = Path.GetFileNameWithoutExtension(city.ImageFile.FileName);
                string extension = Path.GetExtension(city.ImageFile.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                city.image = "~/Image/" + filename;
                filename = Path.Combine(Server.MapPath("~/Image/"), filename);
                city.ImageFile.SaveAs(filename);
                using (hotelEntities8 dc = new hotelEntities8())
                {
                    //if (dc.Cities.Any(x => x.CityName == city.CityName))
                    //{
                    //    ViewBag.DuplicateMessage = "CityName already exist.";
                    //    return View(city);
                    //}
                    dc.Cities.Add(city);
                    dc.SaveChanges();
                }

            }
            catch (Exception ex)
            {
                return View(ex);

            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Successful";
            return RedirectToAction("Index");


        }
         [HttpGet]  
        
        //public ActionResult View(int id)
        //{
        //    City citymodel = new City();
        //    using (hotelEntities2 db =new hotelEntities2())
        //    {
        //        citymodel = db.Cities.Where(x => x.CityId == id).FirstOrDefault();
        //    }
        //    return View(citymodel);
        //}

        // GET: City/Edit/5
        public ActionResult Edit(int id)
        {
            City citymodel = new City();
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Select * from City where CityId = @CityId";
                SqlDataAdapter ada = new SqlDataAdapter(query, con);
                ada.SelectCommand.Parameters.AddWithValue("@CityId", id);
                ada.Fill(dt);
                con.Close();
            }
            if (dt.Rows.Count == 1)
            {
                citymodel.CityId = Convert.ToInt32(dt.Rows[0][0].ToString());
                citymodel.CityName = dt.Rows[0][1].ToString();
               
                return View(citymodel);
            }
            else
            {
                return RedirectToAction("Index");
            }

        }

        // POST: City/Edit/5
        [HttpPost]
        public ActionResult Edit(City citymodel)
        {
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Update City set CityName = @CityName where CityId = @CityId";
                SqlCommand cmd = new SqlCommand(query, con);
                cmd.Parameters.AddWithValue("@CityId", citymodel.CityId);

                cmd.Parameters.AddWithValue("@CityName", citymodel.CityName);

            
                cmd.ExecuteNonQuery();

            }
            return RedirectToAction("Index");
        }

        // GET: City/Delete/5
        public ActionResult Delete(int id)
        {
            City citymodel = new City();
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Select * from City where CityId = @CityId";
                SqlDataAdapter ada = new SqlDataAdapter(query, con);
                ada.SelectCommand.Parameters.AddWithValue("@CityId", id);
                ada.Fill(dt);
                con.Close();
            }
            if (dt.Rows.Count == 1)
            {
                citymodel.CityId = Convert.ToInt32(dt.Rows[0][0].ToString());
                citymodel.CityName = dt.Rows[0][1].ToString();
               
                return View(citymodel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: City/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Delete From City where CityId = @CityId";
                SqlCommand cmd = new SqlCommand(query, con);
                cmd.Parameters.AddWithValue("@CityId", id);


                cmd.ExecuteNonQuery();

            }
            return RedirectToAction("Index");
        }

        public ActionResult Add()
        {
            return View();
        }
    }
}

original/trytry/trytry/Views/City/Add.cshtml
@model trytry.Image

@{
    ViewBag.Title = "Add";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Add</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImagePath, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

original/trytry/trytry/Views/City/Create.cshtml
@model trytry.Models.City

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "City", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CityModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                @Html.LabelFor(model => model.ImageID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ImageID, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ImageID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

original/trytry/trytry/Views/City/Delete.cshtml
@model trytry.Models.City

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CityModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CityId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

original/trytry/trytry/Views/City/Edit.cshtml
@model trytry.Models.City

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>City</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CityId)

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

original/trytry/trytry/Views/City/Index.cshtml
@model IEnumerable<trytry.Models.City>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<div class="container">
    <h2 class="text-center">Cities</h2>
    @foreach (var item in Model)
    {  
        <div class="col-md-3" style="margin-bottom:25px">
            <div class="thumbnail">
                <div class="image" style="margin-bottom:20px">
                    <img class="img-responsive" src="@Url.Content(item.image)" height="350" width="240" />
                </div>
                <div class="caption" style="border-top:3px solid #808080">
                    <h3>@item.CityName</h3>
                    <p>@Html.ActionLink("Edit", "Edit", new { id = item.CityId})`
                    @Html.ActionLink("Delete", "Delete", new { id = item.CityId })</p>
                </div>
                
            </div>
        </div>
    }
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.CityId })*@
    @Html.ActionLink("Add City", "Create")
</p>

<p>@Html.ActionLink("Back To List", "Index", "Admin")</p>

original/trytry/trytry/Views/City/View.cshtml
@model trytry.Models.City

@{
    ViewBag.Title = "View";
}

<h2>View</h2>

<div>
    <h4>City</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.image)
        </dt>

        <dd>
           <img src="@Url.Content(Model.image)" width="250" height="250" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CityId }) |
    @Html.ActionLink("Back to List", "Index")
</p>