original/trytry/trytry/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.SqlClient;
using trytry.Models;
using System.IO;
using System.Data.Entity.Infrastructure;

namespace trytry.Controllers
{
    public class TableController : Controller
    {
        hotelEntities8 dc = new hotelEntities8();
        string connectionstring = @"Data Source=DESKTOP-1M6H1PO\ANUMSQL;Initial Catalog=hotel;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework";
        public ActionResult Index()
        {
            List<tableadmin1> lists = new List<tableadmin1>();
            lists = dc.tableadmin1.ToList();
            return View(lists);
        }

       

        // GET: Table/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Table/Create
        [HttpPost]
        public ActionResult Create(tableadmin1 tablemodel)
        {
            try
            {
                string filename = Path.GetFileNameWithoutExtension(tablemodel.ImageFile.FileName);
                string extension = Path.GetExtension(tablemodel.ImageFile.FileName);
                filename = filename + DateTime.Now.ToString("yymmssfff") + extension;
                tablemodel.image = "~/Image/" + filename;
                filename = Path.Combine(Server.MapPath("~/Image/"), filename);
                tablemodel.ImageFile.SaveAs(filename);
                using (hotelEntities8 dc = new hotelEntities8())
                {

                    dc.tableadmin1.Add(tablemodel);
                    dc.SaveChanges();
                }

            }
            catch (Exception ex)
            {
                return View(ex);

            }
            ModelState.Clear();
            ViewBag.SuccessMessage = "Successful";
            return RedirectToAction("Index");

        }

        // GET: Table/Edit/5
        public ActionResult Edit(int id)
        {
            tableadmin1 tablemodel = new tableadmin1();
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Select * from tableadmin1 where TableId = @TableId";
                SqlDataAdapter ada = new SqlDataAdapter(query, con);
                ada.SelectCommand.Parameters.AddWithValue("@TableId", id);
                ada.Fill(dt);
                con.Close();
            }
            if (dt.Rows.Count == 1)
            {
                tablemodel.TableId = Convert.ToInt32(dt.Rows[0][0].ToString());
                tablemodel.CityName = dt.Rows[0][1].ToString();
                tablemodel.HallName = dt.Rows[0][2].ToString();
                tablemodel.address = dt.Rows[0][3].ToString();

                
                return View(tablemodel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Table/Edit/5
        [HttpPost]
        public ActionResult Edit(tableadmin1 tablemodel)
        {
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Update tableadmin1 set HallName = @HallName, address = @address, CityName = @CityName where TableId = @TableId";
                SqlCommand cmd = new SqlCommand(query, con);
                cmd.Parameters.AddWithValue("@TableId", tablemodel.TableId);

                cmd.Parameters.AddWithValue("@HallName", tablemodel.HallName);

                cmd.Parameters.AddWithValue("@address", tablemodel.address);
                //cmd.Parameters.AddWithValue("@roomtype", hotelmodel.roomtype);
                cmd.Parameters.AddWithValue("@CityName", tablemodel.CityName);

                
                cmd.ExecuteNonQuery();

            }
            return RedirectToAction("Index");
        }

        // GET: Table/Delete/5
        public ActionResult Delete(int id)
        {
            tableadmin1 tablemodel = new tableadmin1();
            DataTable dt = new DataTable();
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Select * from tableadmin1 where TableId = @TableId";
                SqlDataAdapter ada = new SqlDataAdapter(query, con);
                ada.SelectCommand.Parameters.AddWithValue("@TableId", id);
                ada.Fill(dt);
                con.Close();
            }
            if (dt.Rows.Count == 1)
            {
                tablemodel.TableId = Convert.ToInt32(dt.Rows[0][0].ToString());
                tablemodel.CityName = dt.Rows[0][1].ToString();
                tablemodel.HallName = dt.Rows[0][2].ToString();
                tablemodel.address = dt.Rows[0][3].ToString();

               
                return View(tablemodel);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        // POST: Table/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            using (SqlConnection con = new SqlConnection(connectionstring))
            {
                con.Open();
                string query = "Delete From tableadmin1 where TableId = @TableId";
                SqlCommand cmd = new SqlCommand(query, con);
                cmd.Parameters.AddWithValue("@TableId", id);


                cmd.ExecuteNonQuery();

            }
            return RedirectToAction("Index");
        }
    }
}

original/trytry/trytry/Views/Table/Create.cshtml
@model trytry.Models.tableadmin1

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Table", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       // <h4>Table </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
      

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HallName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HallName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HallName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.personno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.personno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.personno, "", new { @class = "text-danger" })
            </div>
        </div>*@

       

        @*<div class="form-group">
            @Html.LabelFor(model => model.budget, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.budget, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.budget, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" required />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

original/trytry/trytry/Views/Table/Delete.cshtml
@model trytry.Models.tableadmin1

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TableModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TableId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TableId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CityName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CityName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HallName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HallName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.personno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.personno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.starttime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.starttime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.endtime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.endtime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.budget)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.budget)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

original/trytry/trytry/Views/Table/Edit.cshtml
@model trytry.Models.tableadmin1

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TableModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TableId)

        <div class="form-group">
            @Html.LabelFor(model => model.CityName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CityName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CityName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.HallName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HallName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HallName, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

       

       

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

original/trytry/trytry/Views/Table/Index.cshtml
@model IEnumerable<trytry.Models.tableadmin1>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_mytemplate.cshtml";
}

<div class="container">
    <h2 class="text-center">Resturant-Tables</h2>
    @foreach (var item in Model)
    {
        <div class="col-md-3" style="margin-bottom:25px">
            <div class="thumbnail">
                <h3 class="text-center">@item.CityName</h3>
                <div class="image" style="margin-bottom:20px">
                    <img class="img-responsive" src="@Url.Content(item.image)" height="350" width="240" />
                </div>
                <div class="caption" style="border-top:3px solid #808080">
                    <h4>@item.HallName</h4>
                    <h5>Address:@item.address</h5>
                    <p>
                        @Html.ActionLink("Edit", "Edit", new { id = item.TableId })`
                    @Html.ActionLink("Delete", "Delete", new { id = item.TableId})
                </p>
            </div>

        </div>
    </div>
    }
</div>

<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.CityId })*@
    @Html.ActionLink("Add Table", "Create")
</p>

<p>@Html.ActionLink("Back To List", "Index", "Admin")</p>